PCAP_INPUT:
    INTERFACE: "eth0"
    SNAP_LEN: 65536
    LOG_ALL_PACKETS: false
    FLUSH_AFTER: "10s"

PROMETHEUS_OUTPUT:
    PROMETHEUS_EXPIRE_AFTER: 20
    PROMETHEUS_EXPIRATION_INTERVAL: 5
    LOCAL_MAC_ADDRESS: ""