{
 "title": "Packet Capture",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Top Source IP's",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incoming_packets_counter[$__range])) by (sourceIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(packets_counter[$__range])) by (sourceIP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Destination IP's",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outgoing_packets_counter[$__range])) by (destinationIP)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(packets_counter[$__range])) by (destinationIP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top source MAC's",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incoming_packets_counter[$__range])) by (sourceMAC)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(packets_counter[$__range])) by (sourceMAC)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top destination MAC's",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outgoing_packets_counter[$__range])) by (destinationMAC)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(packets_counter[$__range])) by (destinationMAC)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum(increase(incoming_packets_counter[$__range])) by (sourcePort))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum(increase(packets_counter[$__range])) by (sourcePort))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, sum(increase(outgoing_packets_counter[$__range])) by (destinationPort))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(20, sum(increase(packets_counter[$__range])) by (destinationPort))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Sent Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(packets_counter[1m])) + sum(increase(incoming_packets_counter[1m])) + sum(increase(outgoing_packets_counter[1m]))",
     "legendFormat": "Packets/min"
    }
   ]
  },
  {
   "title": "Encryption",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(packets_counter[$__range])) by (tlsVersion)",
     "legendFormat": "{{tlsVersion}}"
    },
    {
     "expr": "sum(increase(incoming_packets_counter[$__range])) by (tlsVersion)",
     "legendFormat": "Incoming - {{tlsVersion}}"
    },
    {
     "expr": "sum(increase(outgoing_packets_counter[$__range])) by (tlsVersion)",
     "legendFormat": "Outgoing - {{tlsVersion}}"
    }
   ]
  },
  {
   "title": "TCP Flag",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(packets_counter[$__range])) by (tcpFlag)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(incoming_packets_counter[$__range])) by (tcpFlag)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(outgoing_packets_counter[$__range])) by (tcpFlag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Layer 4 Protocol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(packets_counter[$__range])) by (layer4Protocol)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(incoming_packets_counter[$__range])) by (layer4Protocol)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(outgoing_packets_counter[$__range])) by (layer4Protocol)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}