PCAP_INPUT:
    INTERFACE_NAME: "eth0"
    SNAP_LEN: 65536
    LOG_ALL_PACKETS: false
    FLUSH_AFTER: "10s"
    LOCAL_MAC_ADDRESS: ""

PROMETHEUS_OUTPUT:
    ENABLED: true
    PROMETHEUS_EXPIRE_AFTER: 20
    PROMETHEUS_EXPIRATION_INTERVAL: 5
    PROMETHEUS_METRICS_PORT: 8080